Add dbus-glib dependency to main
It is required through the ipc header and the build will fail without it on Nix:

	In file included from /build/source/src/main/search_sidebar.cc:48:
	/build/source/src/gui/ipc.h:26:10: fatal error: dbus/dbus-glib.h: No such file or directory
	   26 | #include <dbus/dbus-glib.h>
	      |          ^~~~~~~~~~~~~~~~~~
	compilation terminated.