Removing what I believe redundant RTL setting which fails gtk2+xulrunner build.
In svn revno: 4182 (on /branches/webkit) RTL setting has been correctly moved to
the gecko_html_set_parms. But a copy of that code was left in xiphos_html.c With
limited testing (commenting out if) everything works correctly after removing
this redundant copy in xiphos_html.c.

If is it *not* redundant, please fix gtk2+xulrunner build some other way.

I'm getting a fail to build from source when configuring with gtk2 and
xulrunner:

../src/xiphos_html/xiphos_html.c:23:10: error: incomplete definition of type
'struct _GeckoHtmlPriv'
            priv->yelper->SetRTL();
            ~~~~^
In file included from ../src/xiphos_html/xiphos_html.c:1:
In file included from ../src/xiphos_html/xiphos_html.h:38:
../src/xiphos_html/../gecko/gecko-html.h:42:16: note: forward declaration of
'struct _GeckoHtmlPriv'
typedef struct _GeckoHtmlPriv    GeckoHtmlPriv;
               ^
1 error generated.


git-svn-id: http://svn.code.sf.net/p/gnomesword/code/branches/webkit@4222 da23c209-522a-4b7c-92e9-24af42be4764